import React, { useState } from 'react'
import { Code2, ChevronDown, ChevronUp, Copy, Check } from 'lucide-react'

export default function GeneratedQueryBlock({ metadata }) {
  const [open, setOpen] = useState(false)
  const [copied, setCopied] = useState(false)

  const sql = metadata?.sql_queries?.join('\n') || metadata?.sql || "SELECT * FROM fir_cases WHERE location LIKE '%Koramangala%' AND status = 'UNDER_INVESTIGATION';"
  const vectorQuery = metadata?.vector_query || "Semantic match vector search (threshold: 0.85, top_k: 5)"

  const handleCopy = () => {
    navigator.clipboard.writeText(sql)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div style={{
      borderBottom: '1px solid var(--border-dim)',
      background: 'var(--bg-panel)'
    }}>
      <button
        onClick={() => setOpen(!open)}
        style={{
          width: '100%',
          padding: '8px 14px',
          display: 'flex',
          alignItems: 'center',
          justify: 'space-between',
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          color: 'var(--text-secondary)'
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <Code2 size={12} style={{ color: 'var(--cyan)' }} />
          <span style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.06em', fontWeight: 600 }}>
            GENERATED RETRIEVAL QUERY (SQL + VECTOR)
          </span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ fontFamily: 'var(--mono)', fontSize: 9, color: 'var(--text-tertiary)' }}>
            AUTO-GENERATED BY SQL TOOL AGENT
          </span>
          {open ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
        </div>
      </button>

      {open && (
        <div style={{ padding: '0 14px 12px', display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div style={{
            position: 'relative',
            background: 'var(--bg-canvas)',
            border: '1px solid var(--border-dim)',
            borderRadius: 3,
            padding: '10px 12px',
            fontFamily: 'var(--mono)',
            fontSize: 11,
            color: 'var(--cyan)',
            lineHeight: 1.5,
            overflowX: 'auto'
          }}>
            <button
              onClick={handleCopy}
              title="Copy SQL Query"
              style={{
                position: 'absolute',
                top: 6,
                right: 6,
                background: 'var(--bg-row)',
                border: '1px solid var(--border-dim)',
                color: 'var(--text-secondary)',
                borderRadius: 3,
                padding: '3px 6px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: 4,
                fontSize: 10
              }}
            >
              {copied ? <Check size={10} style={{ color: 'var(--green)' }} /> : <Copy size={10} />}
              <span>{copied ? 'COPIED' : 'COPY'}</span>
            </button>
            <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
              {sql}
            </pre>
          </div>
          {vectorQuery && (
            <div style={{ fontFamily: 'var(--mono)', fontSize: 10, color: 'var(--purple)', background: 'rgba(139, 92, 246, 0.05)', padding: '6px 10px', borderRadius: 3, border: '1px solid rgba(139, 92, 246, 0.15)' }}>
              ⚡ HYBRID RAG VECTOR: {vectorQuery}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
